### ISSUE TITLE
Suggestion: Work with P4535992

### ISSUE THREAD

**Issue by ravingdragoon** [Haxxer/FoundryVTT-ItemPiles#1]
It looks like you and @p4535992 are both working on the same thing here, perhaps a team up is in order?

https://github.com/p4535992/foundryvtt-item-placeable

**Comment by p4535992** [comment]
There is a difference in the approach, I wanted to create a customized document bound to the item, @Haxxer's idea is perhaps less brutal, he creates a token linked to the data of one more item from what I am seeing. Anyway if you need a hand just let me know.

**Comment by Haxxer** [comment]
Yeah my idea is to just have an unlinked token with its inventory representing the pile's items. A single item can still be represented with a pile, but perhaps change the token to just use that one item's image as the token's image. I feel leveraging actors as a method of storage means it's more stable long term, and is in line with how Foundry likes to work. It also means that individual systems can implement their own item pile sheets to display the pile's inventory to their own liking.
