### ISSUE TITLE
Module Fails to install from Manifest link

### ISSUE THREAD

**Issue by revilowaldow** [Haxxer/FoundryVTT-ItemPiles#3]
https://github.com/Haxxer/FoundryVTT-ItemPiles/blob/10207a7a9a226d17e265263e31f2904c2892e065/module.json#L41

It doesn't  seem to have been auto-replaced  :'(

**Comment by nirurin** [comment]
Came here to say the same. Seems to be a dead link.

**Comment by Haxxer** [comment]
I have updated the readme to contain the better download link. Please note that this module is still under development, so don't expect it to be stable yet:

`https://github.com/Haxxer/FoundryVTT-ItemPiles/releases/latest/download/module.json`
