### ISSUE TITLE
PF2e system incompatibility

### ISSUE THREAD

**Issue by itamarcu** [Haxxer/FoundryVTT-ItemPiles#4]
With the Pathfinder 2e system, I'm seeing the following issues:
1. A created item pile throws an error when double-clicked instead of opening a sheet.  The code fails with:  `TypeError: Cannot create property 'value' on string '0[object Object]'`
2. The created actor for the token should be of type `loot` instead of `character`
3. Currency attribute - doesn't exist (coins are items on the sheet, of the same kinds as 5e minus electrum)
4. Item type filters - the dnd5e defaults are `spell,feat,class` but in pf2e you could set them as `action,ancestry,background,class,condition,deity,effect,feat,lore,melee,spell,spellcastingEntry`

**Comment by Haxxer** [comment]
Did you change any of the module settings to be compatible with PF2e?

**Comment by Haxxer** [comment]
And there are multiple changes to accommodate currencies and other attributes, more to come in the full release

**Comment by itamarcu** [comment]
> Did you change any of the module settings to be compatible with PF2e?

Nope - just tried it out of the box.  I think you could have the ones I suggested above be the default values put into the settings (with a check based on the system).

Thanks for your work!  I would love to use this module once it's more stable!

**Comment by itamarcu** [comment]
Well, for now we can mark this module as incompatible with PF2e since PF2e already has about half of the features and would require more specialized code to interoperate.

Here's hoping the PF2e devs (or contributors) end up using your module as reference/inspiration to implement the same features!
